helmDefaults:
  createNamespace: true

repositories:
  - name: podinfo
    url: https://stefanprodan.github.io/podinfo

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: itsmethemojo
    url: https://itsmethemojo.github.io/helm-charts/

  - name: jenkinsci
    url: https://charts.jenkins.io

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: bitnami/nginx-ingress-controller
    values:
      - service:
          type: NodePort
          nodePorts:
            http: 30080
            https: 30443

## Application 1
  - name: my-app1
    namespace: my-app1
    chart: ./helm/app
    values:
      - ingress:
          enabled: true
          className: ""
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /
          hosts:
            - host: localhost
              paths:
                - path: /my-app1
                  pathType: Prefix

  - name: my-app2
    namespace: my-app2
    chart: ./helm/app
    values:
      - ingress:
          enabled: true
          className: ""
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /
          hosts:
            - host: localhost
              paths:
                - path: /my-app2
                  pathType: Prefix

  - name: podinfo
    namespace: podinfo
    chart: podinfo/podinfo
    values:
      - ingress:
          enabled: true
          className: ""
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /
          hosts:
            - host: podinfo.local
              paths:
                - path: /
                  pathType: ImplementationSpecific

  - name: jenkins
    namespace: jenkins
    chart: jenkinsci/jenkins
    values:
      - ./jenkins-values.yaml


